# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\repository\ymmeterreader\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_port.setEditable(True)
        self.comboBox_port.setObjectName("comboBox_port")
        self.horizontalLayout_3.addWidget(self.comboBox_port)
        self.pushButton_swithport = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_swithport.setObjectName("pushButton_swithport")
        self.horizontalLayout_3.addWidget(self.pushButton_swithport)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_interval = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_interval.setMinimum(1)
        self.spinBox_interval.setMaximum(30)
        self.spinBox_interval.setObjectName("spinBox_interval")
        self.horizontalLayout_3.addWidget(self.spinBox_interval)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_retry = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_retry.setMinimum(1)
        self.spinBox_retry.setMaximum(10)
        self.spinBox_retry.setProperty("value", 1)
        self.spinBox_retry.setObjectName("spinBox_retry")
        self.horizontalLayout_3.addWidget(self.spinBox_retry)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralWidget)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_curmeter = QtWidgets.QLabel(self.groupBox_2)
        self.label_curmeter.setObjectName("label_curmeter")
        self.horizontalLayout_2.addWidget(self.label_curmeter)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_retry = QtWidgets.QLabel(self.groupBox_2)
        self.label_retry.setObjectName("label_retry")
        self.horizontalLayout_2.addWidget(self.label_retry)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionUpgBpSts = QtWidgets.QAction(MainWindow)
        self.actionUpgBpSts.setObjectName("actionUpgBpSts")
        self.actionUpgTxm = QtWidgets.QAction(MainWindow)
        self.actionUpgTxm.setObjectName("actionUpgTxm")
        self.actionRdSnCfg = QtWidgets.QAction(MainWindow)
        self.actionRdSnCfg.setObjectName("actionRdSnCfg")
        self.actionUpgRdBack = QtWidgets.QAction(MainWindow)
        self.actionUpgRdBack.setObjectName("actionUpgRdBack")
        self.actionRmParsed = QtWidgets.QAction(MainWindow)
        self.actionRmParsed.setObjectName("actionRmParsed")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "配置"))
        self.label.setText(_translate("MainWindow", "串口:"))
        self.pushButton_swithport.setText(_translate("MainWindow", "打开"))
        self.label_2.setText(_translate("MainWindow", "抄表间隔:"))
        self.label_3.setText(_translate("MainWindow", "秒"))
        self.label_4.setText(_translate("MainWindow", "重试次数:"))
        self.label_5.setText(_translate("MainWindow", "抄表报文:"))
        self.lineEdit.setText(_translate("MainWindow", " 68 98 54 20 16 00 00 68 11 04 33 32 34 33 D3 16"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
        self.pushButton_start.setText(_translate("MainWindow", "开始抄表"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "表号"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "状态"))
        self.progressBar.setFormat(_translate("MainWindow", "%v/%m"))
        self.label_6.setText(_translate("MainWindow", "正在抄读:"))
        self.label_curmeter.setText(_translate("MainWindow", "------------"))
        self.label_8.setText(_translate("MainWindow", "次数:"))
        self.label_retry.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", " "))
        self.actionSaveAs.setText(_translate("MainWindow", "SaveAs"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionUpgBpSts.setText(_translate("MainWindow", "upgBpSts"))
        self.actionUpgTxm.setText(_translate("MainWindow", "upgTxm"))
        self.actionRdSnCfg.setText(_translate("MainWindow", "rdSnCfg"))
        self.actionUpgRdBack.setText(_translate("MainWindow", "upgRdBack"))
        self.actionRmParsed.setText(_translate("MainWindow", "rmParsed"))
        self.actionClear.setText(_translate("MainWindow", "clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

